import { sourceChunks, sourceDocuments } from './source-samples';
import type { GuideCard } from './types';

export { sourceChunks, sourceDocuments };

export const baseGuideCards: GuideCard[] = [
  {
    id: 'step-01',
    order: 1,
    title: 'Open the client handoff guide',
    purpose: 'Give the client a single place to begin after delivery.',
    instructions: ['Open the shared handoff link.', 'Review the dashboard sections before editing content.', 'Keep this guide as the first support reference.'],
    completionCheck: 'Client can find the guide and understand where to begin.',
    sourceRefs: ['delivery-checklist#01'],
    reviewStatus: 'approved',
  },
  {
    id: 'step-02',
    order: 2,
    title: 'Edit standard content safely',
    purpose: 'Let the client update routine website content without touching system settings.',
    instructions: ['Edit homepage text blocks, service descriptions, staff bios, and blog posts from the dashboard.', 'Preview changes before publishing.', 'Avoid structural theme settings.'],
    completionCheck: 'One safe text update is previewed without changing theme files.',
    sourceRefs: ['handoff-notes#01'],
    reviewStatus: 'approved',
  },
  {
    id: 'step-03',
    order: 3,
    title: 'Replace images without breaking layout',
    purpose: 'Keep visual updates consistent with the delivered design.',
    instructions: ['Use hero images close to 2400 x 1350 pixels.', 'Use blog images at least 1600 pixels wide.', 'Keep proportions close to the original layout.'],
    completionCheck: 'A replacement image appears without awkward cropping.',
    sourceRefs: ['handoff-notes#03'],
    reviewStatus: 'approved',
  },
  {
    id: 'step-04',
    order: 4,
    title: 'Do not change restricted areas',
    purpose: 'Prevent changes that could affect stability, billing, or domain behavior.',
    instructions: ['Do not edit DNS records.', 'Do not change billing settings.', 'Do not install or edit plugin code without contacting the studio.'],
    completionCheck: 'Client knows which areas require studio confirmation.',
    sourceRefs: ['handoff-notes#02'],
    reviewStatus: 'pending',
  },
  {
    id: 'step-05',
    order: 5,
    title: 'Report bugs with reproduction details',
    purpose: 'Help the studio reproduce and triage issues quickly.',
    instructions: ['Send the page URL.', 'Attach a screenshot.', 'Include device, browser, and a short description of what happened.'],
    completionCheck: 'A bug report contains enough detail for the studio to reproduce it.',
    sourceRefs: ['meeting-transcript#01'],
    reviewStatus: 'approved',
  },
  {
    id: 'step-06',
    order: 6,
    title: 'Understand the 30-day support window',
    purpose: 'Clarify what is covered and what requires a separate quote.',
    instructions: ['Bug fixes for original project scope are covered.', 'New pages, new features, copy edits, SEO, ads, and design revisions are outside the support window.', 'Ask for a separate quote for new work.'],
    completionCheck: 'Client can separate bug-fix support from new work requests.',
    sourceRefs: ['support-faq#01', 'support-faq#02'],
    reviewStatus: 'pending',
  },
  {
    id: 'step-07',
    order: 7,
    title: 'Keep agreement-sensitive issues out of the public guide',
    purpose: 'Avoid publishing claims that should be reviewed against the signed agreement.',
    instructions: ['Do not describe refunds or payment disputes in the public handoff guide.', 'Route agreement-sensitive questions to the project owner.', 'Update this card only after review.'],
    completionCheck: 'Agreement-sensitive topics are flagged before publishing.',
    sourceRefs: ['support-policy#01'],
    reviewStatus: 'pending',
  },
  {
    id: 'step-08',
    order: 8,
    title: 'Ask for help when unclear',
    purpose: 'Give the client a recovery path when a step is confusing.',
    instructions: ['Use the feedback box in the guide.', 'Describe which step is unclear.', 'TraceCue records the feedback for a v1.1 revision proposal.'],
    completionCheck: 'Feedback is captured and turned into a revision proposal.',
    sourceRefs: [],
    reviewStatus: 'pending',
  },
];
