import { sourceChunks, sourceDocuments } from './source-samples';
import type { GuideCard } from './types';

export { sourceChunks, sourceDocuments };

export const baseGuideCards: GuideCard[] = [
  {
    id: 'step-01',
    order: 1,
    title: 'Start with a safe exterior inspection',
    purpose: 'Confirm the unit is safe to inspect before any frontline maintenance begins.',
    instructions: ['Inspect the exterior, intake grille, outlet grille, display panel, and power cord.', 'Confirm intake and outlet areas are clear before running the unit.'],
    completionCheck: 'Exterior condition and airflow openings are checked before operation.',
    sourceRefs: ['maintenance-schedule#01'],
    reviewStatus: 'approved',
  },
  {
    id: 'step-02',
    order: 2,
    title: 'Clean routine surfaces only',
    purpose: 'Keep routine maintenance inside the documented frontline service boundary.',
    instructions: ['Wipe exterior surfaces with a dry lint-free cloth every 30 operating days.', 'Do not pour liquid into the intake, outlet, display panel, or power connector.'],
    completionCheck: 'Exterior surfaces are clean and no liquid has entered the equipment.',
    sourceRefs: ['maintenance-schedule#02'],
    reviewStatus: 'approved',
  },
  {
    id: 'step-03',
    order: 3,
    title: 'Replace the filter when triggered',
    purpose: 'Restore normal airflow using only the approved filter replacement path.',
    instructions: ['Replace the filter when FILTER-90 appears, airflow stays weak after cleaning, or 90 operating days have passed.', 'Power off, unplug, wait two minutes, replace the filter, close the cover, and reconnect power.'],
    completionCheck: 'FILTER-90 clears after reset and normal airflow resumes within one minute.',
    sourceRefs: ['filter-replacement#01', 'filter-replacement#02', 'filter-replacement#03'],
    reviewStatus: 'approved',
  },
  {
    id: 'step-04',
    order: 4,
    title: 'Triage weak airflow without bypassing safeguards',
    purpose: 'Find common airflow causes without creating an unsafe workaround.',
    instructions: ['Check for blocked intake, blocked outlet, saturated filter, or silent mode.', 'Do not bypass the filter to increase airflow.'],
    completionCheck: 'Airflow cause is identified or the case is ready for escalation.',
    sourceRefs: ['fault-triage#02'],
    reviewStatus: 'pending',
  },
  {
    id: 'step-05',
    order: 5,
    title: 'Escalate stop-use conditions immediately',
    purpose: 'Protect frontline users when the source pack identifies safety-critical symptoms.',
    instructions: ['Escalate burning smell, visible smoke, liquid entry, repeated E30 motor fault, damaged power cord, or electrical shock reports immediately.', 'Tell the customer to stop using the unit until support responds.'],
    completionCheck: 'A stop-use case includes a case number and support response window.',
    sourceRefs: ['support-escalation#02', 'support-escalation#03'],
    reviewStatus: 'approved',
  },
  {
    id: 'step-06',
    order: 6,
    title: 'Stay inside frontline service limits',
    purpose: 'Prevent unsupported repair instructions from reaching QR guide users.',
    instructions: ['Frontline staff may clean exterior surfaces, replace approved filters, inspect visible blockage, and record fault details.', 'Do not open sealed electrical, sensor, or motor housings.'],
    completionCheck: 'The guide stops before any sealed housing or electrical repair step.',
    sourceRefs: ['safety-limits#02'],
    reviewStatus: 'pending',
  },
  {
    id: 'step-07',
    order: 7,
    title: 'Do not promise warranty approval',
    purpose: 'Keep warranty-sensitive statements reviewable before publication.',
    instructions: ['Do not promise warranty approval in the QR guide.', 'Collect serial label, service log, fault evidence, and operating conditions for support review.'],
    completionCheck: 'Warranty questions are routed to support review instead of answered as a guarantee.',
    sourceRefs: ['warranty-boundaries#03'],
    reviewStatus: 'pending',
  },
  {
    id: 'step-08',
    order: 8,
    title: 'Capture unclear QR guide feedback',
    purpose: 'Keep the published guide reviewable when frontline users need clarification.',
    instructions: ['Use the feedback box in the guide.', 'Describe which equipment step is unclear.', 'TraceCue records the feedback for a v1.1 revision proposal.'],
    completionCheck: 'Feedback is captured and ready for a source-grounded revision.',
    sourceRefs: [],
    reviewStatus: 'pending',
  },
];
