import type { GuideCard, SourceChunk, SourceDocument } from './types';

export const sourceDocuments: SourceDocument[] = [
  {
    id: 'handoff-notes',
    title: 'Client handoff notes',
    kind: 'handoff',
    excerpt: 'Client can edit homepage text, service descriptions, staff bios, and blog posts from the dashboard. Avoid theme files, DNS records, billing settings, and plugin code unless the studio is contacted.',
  },
  {
    id: 'support-faq',
    title: 'Support FAQ',
    kind: 'faq',
    excerpt: '30-day support covers bug fixes for original project scope. New pages, new features, copywriting changes, SEO campaigns, and major design revisions are not included.',
  },
  {
    id: 'delivery-checklist',
    title: 'Delivery checklist',
    kind: 'checklist',
    excerpt: 'Before handoff, confirm domain, SSL, content editor access, analytics scope, contact form tests, and mobile checks. After handoff, client reviews homepage text and sends launch-blocking issues within five business days.',
  },
  {
    id: 'meeting-transcript',
    title: 'Meeting transcript excerpt',
    kind: 'transcript',
    excerpt: 'Project manager told the client to send exact page URL, screenshot, device, browser, and a short description when reporting issues. Minor copy edits can be quoted separately.',
  },
  {
    id: 'support-policy',
    title: 'Support policy draft',
    kind: 'policy',
    excerpt: 'Covered support includes bug fixes for original scope. Payment disputes follow the signed project agreement and should not be described in a public handoff guide without review.',
  },
];

export const sourceChunks: SourceChunk[] = [
  { id: 'handoff-notes#01', documentId: 'handoff-notes', label: 'Editable content', text: 'Client can edit homepage text blocks, service descriptions, staff bios, and blog posts from the dashboard.' },
  { id: 'handoff-notes#02', documentId: 'handoff-notes', label: 'Restricted areas', text: 'Client should not edit theme files, billing settings, DNS records, or plugin code without contacting the studio.' },
  { id: 'handoff-notes#03', documentId: 'handoff-notes', label: 'Image replacement', text: 'Recommended hero image size is 2400 x 1350 pixels. Blog images should be at least 1600 pixels wide.' },
  { id: 'support-faq#01', documentId: 'support-faq', label: 'Support scope', text: 'The 30-day support window covers bug fixes for work included in the original project scope.' },
  { id: 'support-faq#02', documentId: 'support-faq', label: 'Out of scope', text: 'New pages, new features, copywriting changes, SEO campaigns, paid ads, and major design revisions are not included.' },
  { id: 'delivery-checklist#01', documentId: 'delivery-checklist', label: 'Launch checks', text: 'Client should review homepage text, test contact form, upload one test blog draft, and send launch-blocking issues within five business days.' },
  { id: 'meeting-transcript#01', documentId: 'meeting-transcript', label: 'Bug reports', text: 'Send the exact page URL, screenshot, device, browser, and what happened so the studio can reproduce the issue.' },
  { id: 'support-policy#01', documentId: 'support-policy', label: 'Agreement risk', text: 'Refunds and payment disputes are handled under the signed project agreement and should not be described in the public handoff guide without review.' },
];

export const baseGuideCards: GuideCard[] = [
  {
    id: 'step-01',
    order: 1,
    title: 'Open the client handoff guide',
    purpose: 'Give the client a single place to begin after delivery.',
    instructions: ['Open the shared handoff link.', 'Review the dashboard sections before editing content.', 'Keep this guide as the first support reference.'],
    completionCheck: 'Client can find the guide and understand where to begin.',
    sourceRefs: ['delivery-checklist#01'],
    reviewStatus: 'approved',
  },
  {
    id: 'step-02',
    order: 2,
    title: 'Edit standard content safely',
    purpose: 'Let the client update routine website content without touching system settings.',
    instructions: ['Edit homepage text blocks, service descriptions, staff bios, and blog posts from the dashboard.', 'Preview changes before publishing.', 'Avoid structural theme settings.'],
    completionCheck: 'One safe text update is previewed without changing theme files.',
    sourceRefs: ['handoff-notes#01'],
    reviewStatus: 'approved',
  },
  {
    id: 'step-03',
    order: 3,
    title: 'Replace images without breaking layout',
    purpose: 'Keep visual updates consistent with the delivered design.',
    instructions: ['Use hero images close to 2400 x 1350 pixels.', 'Use blog images at least 1600 pixels wide.', 'Keep proportions close to the original layout.'],
    completionCheck: 'A replacement image appears without awkward cropping.',
    sourceRefs: ['handoff-notes#03'],
    reviewStatus: 'approved',
  },
  {
    id: 'step-04',
    order: 4,
    title: 'Do not change restricted areas',
    purpose: 'Prevent changes that could affect stability, billing, or domain behavior.',
    instructions: ['Do not edit DNS records.', 'Do not change billing settings.', 'Do not install or edit plugin code without contacting the studio.'],
    completionCheck: 'Client knows which areas require studio confirmation.',
    sourceRefs: ['handoff-notes#02'],
    reviewStatus: 'pending',
  },
  {
    id: 'step-05',
    order: 5,
    title: 'Report bugs with reproduction details',
    purpose: 'Help the studio reproduce and triage issues quickly.',
    instructions: ['Send the page URL.', 'Attach a screenshot.', 'Include device, browser, and a short description of what happened.'],
    completionCheck: 'A bug report contains enough detail for the studio to reproduce it.',
    sourceRefs: ['meeting-transcript#01'],
    reviewStatus: 'approved',
  },
  {
    id: 'step-06',
    order: 6,
    title: 'Understand the 30-day support window',
    purpose: 'Clarify what is covered and what requires a separate quote.',
    instructions: ['Bug fixes for original project scope are covered.', 'New pages, new features, copy edits, SEO, ads, and design revisions are outside the support window.', 'Ask for a separate quote for new work.'],
    completionCheck: 'Client can separate bug-fix support from new work requests.',
    sourceRefs: ['support-faq#01', 'support-faq#02'],
    reviewStatus: 'pending',
  },
  {
    id: 'step-07',
    order: 7,
    title: 'Keep agreement-sensitive issues out of the public guide',
    purpose: 'Avoid publishing claims that should be reviewed against the signed agreement.',
    instructions: ['Do not describe refunds or payment disputes in the public handoff guide.', 'Route agreement-sensitive questions to the project owner.', 'Update this card only after review.'],
    completionCheck: 'Agreement-sensitive topics are flagged before publishing.',
    sourceRefs: ['support-policy#01'],
    reviewStatus: 'pending',
  },
  {
    id: 'step-08',
    order: 8,
    title: 'Ask for help when unclear',
    purpose: 'Give the client a recovery path when a step is confusing.',
    instructions: ['Use the feedback box in the guide.', 'Describe which step is unclear.', 'TraceCue records the feedback for a v1.1 revision proposal.'],
    completionCheck: 'Feedback is captured and turned into a revision proposal.',
    sourceRefs: [],
    reviewStatus: 'pending',
  },
];
